name: daily
run-name: daily collecting data from gov pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 0 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:

      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v4

      - name: MFCR data
        run: bin/mfcr.sh

      - name: SÚKL data
        run: bin/sukl.sh

      - name: USKVBL data
        run: bin/uskvbl.sh

      - name: SZPI data
        run: bin/szpi.sh

      - name: Others
        run: bin/others.sh

      - name: generate RPZs
        run: |
          cat csv/mfcr.csv | bin/csv2rpz.sh > rpz/mfcr.rpz
          cat csv/sukl.csv | bin/csv2rpz.sh > rpz/sukl.rpz
          cat csv/uskvbl.csv | bin/csv2rpz.sh > rpz/uskvbl.rpz
          cat csv/szpi.csv | bin/csv2rpz.sh > rpz/szpi.rpz
          cat csv/others.csv | bin/csv2rpz.sh > rpz/others.rpz
          cat csv/*.csv | bin/csv2rpz.sh > rpz/all.rpz

      - name: smoke check
        run: bin/check.sh

      - name: get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: GIT commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -A
          git commit -m "daily commit ${{ env.date }}" || true
          git push origin master || true
